### ISSUE TITLE
can acme-client exist besides official letsencrypt client

### ISSUE THREAD

**Issue by centminmod** [kelunik/acme-client#1]
Is there any conflicts or issues having official letsencrypt client installed + this acme-client ?

could renewal be done by either official letsencrypt client OR acme-client interchangeably ?

looking at alternatives for low memory 128MB to 512MB VPS systems https://github.com/letsencrypt/letsencrypt/issues/1081

can I use same email address to register with official letsencrypt client AND acme-client ?

cheers

George

**Comment by kelunik** [comment]
This client stores all data locally in `./data`, so there are no conflicts. I wouldn't try to use one client on the other's data store, they're probably not compatible.

Registering a new account with the same mail address is always allowed for Let's Encrypt.

**Comment by centminmod** [comment]
sweet thanks @kelunik :)
