### ISSUE TITLE
Support PHP 5.x

### ISSUE THREAD

**Issue by ghost** [kelunik/acme-client#11]
It is imperative to support PHP 5.x because that is what almost all real servers use. PHP 7 may take another year (or two) to reach enterprise Linux distros. We all run PHP 7 on our desktop computers, but this project is related to certificates on servers.

Forcing PHP 7 as a requirement is really killing this project.

**Comment by PeeHaa** [comment]
The `renew` branch is 5.x compatible'ish https://github.com/kelunik/acme-client/issues/4#issuecomment-166974432. Also I would assume it will never target 5.x, but rather a 5.supported php version.

And at least debian is already working on [getting 7 in](https://packages.debian.org/search?keywords=php7.0) btw.

**Comment by PeeHaa** [comment]
BTW I can see the usefulness (if there is enough demand for it) for >= php 5.supported version.

**Comment by kelunik** [comment]
Right, the `renew` branch is already somehow PHP 5.5 compatible, but it's not stable, things will change. I try to find time finishing the changes I want to make, but my overall open-source activity is unfortunately currently pretty low.

**Comment by kelunik** [comment]
If you use PHP 5.5+, use `git checkout renew && git checkout HEAD^`.

**Comment by kfeutz** [comment]
Hey @kelunik, any update on your most recent local changes for 5.5+?

**Comment by kelunik** [comment]
Changes are finally in `master`.

I renamed `master` to `0.1.x` and pushed my local things to `master`, also tagged `0.1.0` and `0.2.0`.

Had thrown away my previous local changes and remade them, I think the `check` mechanism is better than the previous `renew` mechanism with various config files.
