### ISSUE TITLE
Certificate only requested for first domain listed, no SAN

### ISSUE THREAD

**Issue by accolon** [kelunik/acme-client#2]
When I use acme-client to request a certificate for several domains at once (e.g. with --domains mysite.com,www.mysite.com), I only get a certificate for the first domain in the list.

While challenge/auth for every domain listed takes place, the X509v3 Subject Alternative Name field in the resulting certificate contains just the same single value as the CN field.

I'm not sure whether this is a problem with the acme-client or the library (or if I'm just being stupid). If you need any additional information, I'd be glad to help.

**Comment by kelunik** [comment]
I'm pretty sure this is a problem with my library, thanks for reporting. I'll investigate.

**Comment by kelunik** [comment]
See http://stackoverflow.com/q/34323195/2373138.

**Comment by accolon** [comment]
Indeed, the workaround is not that elegant, but at least it seems to work. The default openssl.cnf contains a lot of stuff that is either unnecessary or replaced by values from the call, so I wonder how much the temporary cnf can be slimmed down.

Unfortunately, my PHP is too bad for a pull request, so I'll leave the clean implementation to you. ;-)
