### ISSUE TITLE
More configuration file examples for auto

### ISSUE THREAD

**Issue by PalleZ** [kelunik/acme-client#30]
I really like the new auto option but I have some issues with getting it to work. Maybe it's because I'm not so good at YAML. It would be nice with some more examples on how to configure different cases.

An example:

I want to have two sites with different certificates so I put this in config file:

```
certificates:
    - paths:
       - /www/example1: site1.example.org
       - /www/example2: site2.example.org
```

But then I get:

Issuance for the following domains failed: site1.example.org, site2.example.org
Reason: exception 'Kelunik\Acme\AcmeException' with message 'Unexpected exit code (1) for ''/usr/bin/php' './acme-client.phar' 'issue' '--server' 'letsencrypt' '--storage' '/etc/acme' '--domains' 'site1.example.org, site2.example.org' '--path' '0:1''.

If I try:

```
certificates:
    - paths:
       /www/example1: site1.example.org
       /www/example2: site2.example.org
```

I get both sites in one certificate with name from the first site. Which I guess makes sense (at least if one is used to the issue command) and which will probably work as long as I don't have more than the limit of sites for one certificate.

Tested on 0.2.7

**Comment by kelunik** [comment]
Thanks for the feedback! I think I'll add more examples and more error checking in the CLI tool itself.

If you want to have two separate certificates, you need to have the arrays one step above:

``` yml
certificates:
 - paths:
    /www/example1: site1.example.org
 - paths:
    /www/example2: site2.example.org
```

JSON equivalent which should work, as JSON is a subset of YAML:

``` json
{
  "certificates": [{
    "paths": {
      "/www/example1": "site1.example.org"
    }
  }, {
    "paths": {
      "/www/example2": "site2.example.org"
    }
  }]
}
```

**Comment by PalleZ** [comment]
Thanks, I thought I tried that combination but obviously not.

**Comment by kelunik** [comment]
Next release will contain a helpful error message if you try to attempt with your previous configuration.
