### ISSUE TITLE
Auto with -c flag requires -s and --storage flags

### ISSUE THREAD

**Issue by PalleZ** [kelunik/acme-client#35]
Running auto command with -c flag makes -s and --storage flags to be required despite this information being available in config file. In case of conflict between flag and config file what will be used?

-bash-4.1$ sudo ./acme-client.phar auto -s letsencrypt:staging -c /www/prod/external/lib/acme-client/my_prod_server/acme-client.yml 
Usage: ./acme-client.phar auto [-c config, --config config] [-s server, --server server] [--storage storage]

Required Arguments:
    -s server, --server server
        ACME server to use for registration and issuance of certificates.
    --storage storage
        Storage directory for account keys and certificates.
    -c config, --config config
        Configuration file to read.

The following arguments are required: [--storage storage].

**Comment by PalleZ** [comment]
Forgot to add that this has been tested on 0.2.8 and current master (commit 74b275cf077e3828ed1332be73634fb37560a8fe)

**Comment by kelunik** [comment]
Sorry for the long delay. I just pushed changes that should resolve this issue. You can test them using the `master` branch. I will release a new version once I have the remaining issues resolved and tested.

**Comment by PalleZ** [comment]
Tested OK on master. Thanks for fix.

**Comment by kelunik** [comment]
@PalleZ, new release is also released.
