### ISSUE TITLE
Command 'issue' doesn't report errors when creating challenge file

### ISSUE THREAD

**Issue by oldnomad** [kelunik/acme-client#37]
When challenge file creation fails for any reason (non-existing document root, wrong permissions, and so on), `ChallengeStore::doPut()` throws a `ChallengeStoreException` and corresponding promise returned by `ChallengeStore::put()` fails. However, `Issue::solveChallenge()` doesn't check this promise, so the challenge process fails on self-check (`yield $acme->verifyHttp01Challenge($domain, $token, $payload);`) without any indication on why the challenge file wasn't created.

**Comment by kelunik** [comment]
Sorry for the long delay. You're right, we didn't even wait for the `put` to complete. That might have ended up with a race condition if non-blocking extensions are used for IO.
