### ISSUE TITLE
auto docs cron example not posix compliant

### ISSUE THREAD

**Issue by jtarobaze** [kelunik/acme-client#39]
The docs example for a cron entry to run the auto command:

``` bash
0 0 * * * acme-client auto; exit=$?; if [[ $exit = 4 ]] || [[ $exit = 5 ]]; then service nginx reload; fi
```

is not ideal, because it uses a bashism: `[[`.

At least Ubuntu and maybe others use dash as the system shell, so this command fails.

Single `[` works fine and is POSIX compliant. So:

``` sh
0 0 * * * acme-client auto; exit=$?; if [ $exit = 4 ] || [ $exit = 5 ]; then service nginx reload; fi
```

works in bash or dash and probably most other shells.

**Comment by kelunik** [comment]
Would you mind providing a PR? Maybe we could also add a note about `PATH` which might not be set correctly.

**Comment by spikyjt** [comment]
Sorry, just realised I submitted this ticket with my work Github account. I'll add the PR shortly with this account, which is my personal one.
