### ISSUE TITLE
PHP >=7.0.0 

### ISSUE THREAD

**Issue by tahongawaka** [kelunik/acme-client#4]
Is there anything in this package that _actually_ requires PHP 7.0.0?

**Comment by kelunik** [comment]
Scalar type declarations, return type declarations and probably somewhere `??` or so. There's a `renew` branch, it should already be PHP 5.5 compatible, but it's not ready to be merged into `master` right now.

**Comment by Maumtrasna** [comment]
As long as tthe PHP 7.0 requirement exists it should be mentioned on the front page.

**Comment by kelunik** [comment]
Feel free to submit a PR. :-)

**Comment by Ocramius** [comment]
https://github.com/kelunik/acme-client/blob/b1e3839323462771985398d49fb706aba4976810/composer.json#L5 states the requirement really clearly: no need for `README` updates for something that obvious ;-)
