### ISSUE TITLE
Possible to Install New Cert on Port <> 80?

### ISSUE THREAD

**Issue by ComputerTinker** [kelunik/acme-client#42]
Thanks for writing this PHP client. It appears to be just what I need, but the problem I'm having is that my web server is not running on port 80, and when trying to install a cert I get an error to that effect:

`Connection to tcp://myserver.com:80 failed: timeout exceeded (30000 ms)
exception 'Kelunik\Acme\AcmeException' with message 'Issuance failed, not all challenges could be solved.' in phar://C:/LetsEncrypt/acme-client.phar/src/Commands/Issue.php:104`

If I try to include the port number in the domain, it doesn't like that either:

`exception 'Kelunik\Acme\AcmeException' with message 'Couldn't resolve the following domains to an IPv4 nor IPv6 record: 1234' in phar://C:/LetsEncrypt/acme-client.phar/src/Commands/Issue.php:197`

Any help appreciated. Thanks!

**Comment by kelunik** [comment]
This is a limitation by the ACME protocol, it only allows HTTP validation using port 80. Validating on other than the well-known ports 80 for HTTP might be a security issue with shared hosts that aren't configured properly, where anyone can open other ports.

There are other challenge types like SNI over port 443 or a DNS challenge, but those are not supported by this client.

What's the reason for not using port 80? Do you have (another) server running on port 80?

**Comment by ComputerTinker** [comment]
The reason we use a non-standard port on this server is because it's a QA server that's meant for use only by select clients, not the general public.

Looks like I'll have to find a client that supports the DNS challenge method. I see that the Perl client does, but it's giving me some errors when I try to install it...  Anyway, thanks for the response.

**Comment by kelunik** [comment]
In that case you can just use the certificate of the primary server and you'll be fine. If you want a separate certificate, you can either use the primary web root for verification or redirect `/.well-known/acme-challenge` to the new port, but it'll be hard to differentiate. I'd just use the certificate you already obtained for the primary service running on port 80.

**Comment by ComputerTinker** [comment]
There is no primary server running on port 80, and port 80 isn't open in our firewall. The only server we have from our location is the QA server running on an alternate port. Once the code has been QA'd by the client we promote it to a production server which is hosted elsewhere.

**Comment by kelunik** [comment]
What's the reason to use a non-standard port then? Security though obscurity?

**Comment by ComputerTinker** [comment]
Yes.

**Comment by kelunik** [comment]
The hostname will anyway be public, because Let's Encrypt publishes all certificates in CT logs. Security through obscurity doesn't really add any security.

I think I'd propose to use port 80 / 443 and use something like basic auth for the client.

**Comment by ComputerTinker** [comment]
Yes, I know, I suggested that too, but it's not my decision.  ;-)

**Comment by kelunik** [comment]
But in any way, you could just open port 80 purely for the challenges and not host anything there, works, too.

**Comment by kelunik** [comment]
Either way, I'm closing this now, as possible workarounds have been mentioned.
