### ISSUE TITLE
No MX record defined for 'domain.com'

### ISSUE THREAD

**Issue by Globulopolis** [kelunik/acme-client#43]
Using the last release I got this error at the first step.
Running `php acme-client.phar setup --email web@domain.com` throws me 
`exception 'Kelunik\Acme\AcmeException' with message 'No MX record defined for 'domain.com'' in phar://D:/WWW/le/acme-client.phar/src/Commands/Setup.php:84`
MX-record for domain allready exists.

What's wrong?

**Comment by kelunik** [comment]
Can you share the domain? Did you create the record only shortly before getting the error?

**Comment by Globulopolis** [comment]
libra.ms domain. And no.

**Comment by kelunik** [comment]
Thanks for reporting. This one is related to #44. It just showed the same error message for every DNS failure instead of just when no record is found.
