### ISSUE TITLE
Option to specify nameserver timeout

### ISSUE THREAD

**Issue by Globulopolis** [kelunik/acme-client#44]
Sometimes on slow connections I get this error `Name resolution timed out`. Is any options available for customize network timeouts(if this is network timeouts of course)?

**Comment by kelunik** [comment]
Are you using Linux? In that case you can use the [`options timeout:n`](http://man7.org/linux/man-pages/man5/resolver.5.html) setting in `/etc/resolv.conf`, `amphp/dns` respects that setting.

**Comment by Globulopolis** [comment]
No, I'm on Windows platform.

**Comment by kelunik** [comment]
I've released [`v0.3.0-alpha.3`](https://github.com/kelunik/acme-client/releases/tag/v0.3.0-alpha.3) which includes an upgrade to Amp v2 and a completely rewritten `amphp/dns`, however it requires PHP 7.0 now. Could you test whether the problem still exists?

I believe the old `amphp/dns` implementation may have been buggy in that regard, so maybe a timeout setting isn't required.

**Comment by kelunik** [comment]
I'm closing this issue. If there's a need to modify the DNS timeout, there are likely other problems and the timeout isn't really the issue.
