### ISSUE TITLE
Issuance Failed Challenge

### ISSUE THREAD

**Issue by gavinggordon** [kelunik/acme-client#45]
I keep getting the below error, upon attempting to issue certificates for any number of my domains.

``` bash
   $ acme-client issue --bits 4096 -d www.URL1.com:URL1.com:www.URL2.com:URL2.com -p $HOME/public_html:$HOME/addon_domains/URL2
   selfVerify failed, please check http://PLACEHOLDER-URL.com/.well-known/acme-challenge/CmheUieDk5C-46IPqyiCsAByScw--Ete_2J43FhSnyE.                                   
   Challenge marked as invalid!                                                                                                                                     
   Challenge marked as invalid!                                                                                                                                     
   exception 'Kelunik\Acme\AcmeException' with message 'Issuance failed, not all challenges could be solved.' in phar:///$HOME/bin/acme-client/src/Commands/Issue.php:104  
```

The specified directories exist and also contain a _**.well-known/acme-challenge**_ directory with read/write permissions; yet, no challenges are even being written to those directories, which is likely resulting in the issue.

**Comment by gavinggordon** [comment]
Nevermind; Fixed the problem. It was an error on my end.

**Comment by kelunik** [comment]
@gavinggordon Could you explain the issue? Maybe I can add a better error message or others having similar issues can read it at least.

**Comment by fernandodrf** [comment]
I am having the same problem to renew my Let's Encrypt certificates:

```
$ php acme-client/bin/acme issue -s letsencrypt -d URL.com:www.URL.com -p $HOME/public_html:$HOME/public_html

    Providing payload at http://www.URL.com/.well-known/acme-challenge/ZGjskxbRBJcDPyrJVBpPB2DFCAZrQAzlmOVuZsQUW4k
    Providing payload at http://URL.com/.well-known/acme-challenge/mQ40x_WaUFcJeWGdxOf5sSPIzuYJ7id547CFmMmMNoQ
selfVerify failed, please check http://www.URL.com/.well-known/acme-challenge/ZGjskxbRBJcDPyrJVBpPB2DFCAZrQAzlmOVuZsQUW4k.
selfVerify failed, please check http://URL.com/.well-known/acme-challenge/mQ40x_WaUFcJeWGdxOf5sSPIzuYJ7id547CFmMmMNoQ.
Kelunik\Acme\AcmeException: Issuance failed, not all challenges could be solved. in $HOME/acme-client/src/Commands/Issue.php:104
```

Any ideas? The server has PHP 7.1

**Comment by kelunik** [comment]
@fernandodrf Did the client create `.well-known/acme-challenge` in the right place? If you place a file inside it, can you access it through your web server?

**Comment by NeilStrickland** [comment]
I had a similar problem.  I also thought that the script was not actually putting anything in .well-known/acme-challenge, but after inspecting the source code, I understood that the relevant catch() clause deletes the file before re-throwing the error.  While that keeps things tidy, it also makes it harder to understand what is happening.  Later I understood that the firewall configuration for this development machine was preventing the letsencrypt server from fetching the challenge file.  It would be useful to have a more comprehensible error message that mentions this possibility explicitly.
