### ISSUE TITLE
Option to specify nameserver

### ISSUE THREAD

**Issue by imbrish** [kelunik/acme-client#47]
Dependency of your repo, `amphp/dns`, behaves weirdly on my local pc and hosting, despite that php native `gethostbyname` works without any problems. It persistently gives me 'All name resolution requests failed' for some servers, let it be `google.com` or `github.com`.

Would be cool if it was possible to set custom nameserver by some additional command line option ;)

**Comment by Lodesys** [comment]
Sounds similar to my issue -- https://github.com/kelunik/acme-client/issues/46

**Comment by kelunik** [comment]
Sorry for the long, long delay. `amphp/dns` is really fundamental for almost all Amp-based applications, issues should therefore rather be fixed there than adding workarounds like additional options.

Do you happen to run on Windows?

**Comment by imbrish** [comment]
I develop on windows but I am not sure anymore whether the problem occurred there or in production environment on linux. I remember that I tried looking for issue in `amphp/dns`, which however got too complicated for me very quickly.

Changing nameserver fixed the problem anyway. It is easily doable in `amphp/dns`, however I had to modify your client locally to achieve it. Thus I thought that a config option would be neat.

**Comment by kelunik** [comment]
@imbrish I've released [`v0.3.0-alpha.3`](https://github.com/kelunik/acme-client/releases/tag/v0.3.0-alpha.3) which includes an upgrade to Amp v2 and a completely rewritten `amphp/dns`, however it requires PHP 7.0 now. Could you test whether the problem still exists?

**Comment by imbrish** [comment]
@kelunik I'll test and let you know as soon as I move the project to PHP 7 as well!

**Comment by kelunik** [comment]
If you still see issues, please open an issue at [`amphp/dns`](https://github.com/amphp/dns).
