### ISSUE TITLE
deprecate the --server argument

### ISSUE THREAD

**Issue by kaystrobach** [kelunik/acme-client#5]
as  letsencrypt is now in production mode, the --server argument should be deprecated or not set as mandatory to make the commands more readable :smile:

**Comment by kelunik** [comment]
Let's Encrypt is currently the only CA implementing ACME, but as soon as others appear, a default will be bad. The `renew` branch uses a slightly different approach saving it to a config file, but it's not ready to be merged yet. Additionally, the `renew` branch removes multi account setups, but I'm not sure that thing will stay.

**Comment by kaystrobach** [comment]
How about introducing a ca flag? Making the server optional so you just need to remeber letsencrypt instead of the really longish url ;)

Multiple accounts should be supported ;)

----- Originale Nachricht -----
Von: Niklas Keller notifications@github.com
Gesendet: 02.01.2016 - 22:42
An: kelunik/acme-client acme-client@noreply.github.com
Betreff: Re: [acme-client] deprecate the --server argument (#5)

**Comment by ekohl** [comment]
It was also very useful to test against the staging server when I was developing. You could have a generic `--server letsencrypt:production` or `--server letsencrypt:staging` alias for simplicity.

**Comment by kelunik** [comment]
I will totally rewrite the server selection thing, I think.

My current plans:
- Provide standards for all known CAs (suggested `name:env`)
- There will be a single account per CA to keep things simple (you can always clone the repository twice)
- Config for issuance will be written to a repository global config to keep things simple and have a nice overview. This config can then be used to choose the same parameters on renewal.

I have parts of it already locally, but in a very unclean state based on the `renew` branch.

**Comment by ekohl** [comment]
> There will be a single account per CA to keep things simple (you can always clone the repository twice)

Could also be solved by a configurable data directory instead of hard-coding it to the directory root. Might even be a good idea in general.

**Comment by kelunik** [comment]
Yeah, already thought about that. That way we could even distribute it as `.phar` archive.

**Comment by kelunik** [comment]
There are shortcuts now in `master`.
