### ISSUE TITLE
Please help, i keep getting this error. 

### ISSUE THREAD

**Issue by Jordychoo** [kelunik/acme-client#50]
Providing payload at http://www.mydomain.com/.well-known/acme-challenge/7-smHbOwopaRKn2-zTmvxEvLe83x2HjG875uecm6Yk8
    Providing payload at http://mydomain.com/.well-known/acme-challenge/sl9WKbCDYyK-DEObXWIHTaCiukm0vjQvMAzQDxk0uW8

selfVerify failed, please check http://www.mydomain.com/.well-known/acme-challenge/7-smHbOwopaRKn2-zTmvxEvLe83x2HjG875uecm6Yk8.
selfVerify failed, please check http://mydomain.com/.well-known/acme-challenge/sl9WKbCDYyK-DEObXWIHTaCiukm0vjQvMAzQDxk0uW8.
Kelunik\Acme\AcmeException: Issuance failed, not all challenges could be solved. in /home/u57374xxxx/acme-client/src/Commands/Issue.php:106

**Comment by kelunik** [comment]
Did the client create `.well-known/acme-challenge` in the path you specified? Can you access a file through your web server if you put it into that directory?

**Comment by Jordychoo** [comment]
Yes, the client create .well-known/acme-challenge in  /public_html path. No, I'm unable to access it through internet.

**Comment by kelunik** [comment]
In that case you configured something wrong that makes these files inaccessible. Any files you create within that directory must be accessible via the internet to prove domain control.

**Comment by Jordychoo** [comment]
How can I do that please? I don't know

**Comment by kelunik** [comment]
Which web server do you use? Are you on a shared host?

**Comment by Jordychoo** [comment]
Yes, i'm on shared host. I use hostinger as web server

**Comment by Jordychoo** [comment]
Are you still there?

**Comment by kelunik** [comment]
Yes, I am. I do check GitHub often, but not every minute. If you can't change the configuration, ask your provider any access to those is blocked.

**Comment by MinionWarrior** [comment]
Having also the same prob

**Comment by miloske85** [comment]
I had the same problem, it drove me nuts for a whole day. Turned out I had set up .htaccess to allow access only from my IP. Don't know if this is issue in your case, but it's one thing you might check. I don't know what IP is acme-client using, but looking at logs I see that now it was 66.133.109.36. This could be a static IP, or it could be a range of IPs. Does someone know this?

I could set up cron script to disable my .htaccess files, run acme-client and then re-enable them, but it would be easier to just whitelist a range of IPs.

**Comment by kelunik** [comment]
@miloske85 The server has to be accessible from everywhere. The used IP can and will change and it might even be multiple IPs in the future.

**Comment by ghost** [comment]
Just to add a comment here, I had exacly same issue and I found that I have not configured DNS properly. 
If anyone has same issue, please check DNS is pointing to your hosting correctly.

**Comment by kelunik** [comment]
Closing this now.
