### ISSUE TITLE
'issue' of multiple domains does not work when in 'wrong order'

### ISSUE THREAD

**Issue by fh-fh** [kelunik/acme-client#57]
When doing as root:
`acme-client issue -d f.domain.com:h.domain.com -p /var/www/html:/var/www/html`
or 
`acme-client issue -d f.domain.com:h.domain.com -p /var/www/html`
you get:
   _Providing payload at http://h.domain.com/.well-known/acme-challenge/VOC........
   h.domain.com is now authorized._
(red)_Could not obtain directory.
exception 'Kelunik\Acme\AcmeException' with message 'Issuance failed, not all challenges could be solved.' in phar:///usr/local/bin/acme-client/src/Commands/Issue.php:106_(/red)
But:
`acme-client issue -d h.domain.com:f.domain.com -p /var/www/html`
works fine.
I use:  php 5.6.30-0+deb8u1
acme-client.yml: 
  storage: /etc/acme
  server: letsencrypt
I changed my real used domain in this text to 'domain.com'.

**Comment by kelunik** [comment]
Did you verify that this was not just a hick-up and a repeated attempt with the same order might have succeeded?

**Comment by fh-fh** [comment]
I tested it several times before I found that it was a problem of the order of the domains.
I tested with two different domains where I used before the 'wrong order' and got the error; when I change the order it works now.
I use kelunik/acme-client @ 0.2.14 (built: May 10th 2017 10:32:52 CEST)

**Comment by kelunik** [comment]
Could you check it again? Maybe use the staging server, so it doesn't count towards your rate limit.
