### ISSUE TITLE
make it possible to run the script without root privileges

### ISSUE THREAD

**Issue by kaystrobach** [kelunik/acme-client#6]
for some shared hosting envs it would be awesome to have the ability to run the client as non root user

**Comment by kaystrobach** [comment]
took a look into the code, and i think, basicly the chown statements need to be removed if the current user is not a root user (posix_id != 0)

**Comment by kelunik** [comment]
You're right, already thought about that. Maybe a special flag like `--no-root` would be required to prevent file permission issues due to missing `sudo` in other environments.

**Comment by kaystrobach** [comment]
I will take a look into that one, at first i will only check if uid ===0 if so do a chown if not simple not do it 

----- Originale Nachricht -----
Von: Niklas Keller notifications@github.com
Gesendet: 02.01.2016 - 22:43
An: kelunik/acme-client acme-client@noreply.github.com
Betreff: Re: [acme-client] make it possible to run the script without root privileges (#6)

**Comment by xgin** [comment]
I'd like to discourage you of usage posix functions: it breaks compatibility with Windows.
Wrapping in function_exists could be suitable workaround.

**Comment by kelunik** [comment]
It doesn't work without those on Unix systems. I don't know if checking for Windows or with `function_exists` is better. Having a build without `posix` enabeld on Linux will probably fail then, because of wrong privileges.

**Comment by kaystrobach** [comment]
@kelunik the files will have the current user as owner if there is no chmod done, so it should be ok.
IMHO this is the only way to ensure, that it can be used on shared hosting envs, often there is no way to use chown :(

and in those envs you will then upload the ssl certificates via a webinterface to setup all the stuff.

**Comment by kelunik** [comment]
Yes, but in all other environments you're usually not logged in as the webserver's user. And then all those files will be owned by your operations account. That's why I prefer a explicit `--no-root` or `--no-sudo` or `--no-chown` flag currently.

**Comment by kaystrobach** [comment]
agreed

**Comment by kelunik** [comment]
Should be resolved by #14.
