### ISSUE TITLE
Issuance failed, not all challenges could be solved

### ISSUE THREAD

**Issue by rafamss** [kelunik/acme-client#60]
Hi folks,

I'm trying configure the certification on my hosting, but all time I received the error below. Could you provide me some help?

`selfVerify failed, please check http://webmail.mydomain/.well-known/acme-challenge/xVqhrAXQ1VGvee2x-I2tqRnTf_Ywqu5E0GLepS37168.
Kelunik\Acme\AcmeException: Issuance failed, not all challenges could be solved. in /home/myhome/downs/acme-client/src/Commands/Issue.php:106`

[ ]s
R. Martins

**Comment by kelunik** [comment]
Do you see `.well-known/acme-challenge` in your document root? If you place a file there, can you open it from the browser?

**Comment by rafamss** [comment]
@kelunik this directory is empty in my machine.

**Comment by kelunik** [comment]
Yes, that's expected, the client clears all challenges. But if you create a file there, can you access it in your browser?

**Comment by rafamss** [comment]
I can access the file that I created there.
`http://mydomain/.well-known/acme-challenge/test.txt`

**Comment by kelunik** [comment]
Does the user running the client has permission to create files there, too?

**Comment by rafamss** [comment]
Yes!

**Comment by rafamss** [comment]
@kelunik Do you found something that could be generating this error?

**Comment by kelunik** [comment]
The `selfVerify` does really not more than checking the response body: https://github.com/kelunik/acme/blob/c5abcd1e68f78e66a17e5a104ed12d16e791ad24/lib/Verifiers/Http01.php#L76-L88

Could you try running via a `git clone` version instead of using the PHAR (in case you used it before) and temporarily remove `yield $challengeStore->delete($token);` in https://github.com/kelunik/acme-client/blob/f4cabf755b0615ef1e33a0efbbfdeb2a8081cc33/src/Commands/Issue.php#L167-L175 and see whether the file is actually created?

**Comment by Ayesh** [comment]
Does your web server logs report any request from LE?

**Comment by kelunik** [comment]
@Ayesh LE isn't even involved at that stage, `selfVerify` happens before LE is contacted.

**Comment by rafamss** [comment]
I'll try this later and send feedback to you. By the way, this error can be associated with a use for this certificate to webmail? I say this because I'm trying to put this certificate in my personal webmail URL, something like this: `webmail.mydomain.com`. Other point, I'm using a shared hosting (hostinger) for my domains.

Tks guys!

**Comment by kelunik** [comment]
As long as that domain correctly resolves to the given document root, everything should be fine.

**Comment by tolidano** [comment]
I am having the same problem again. Obviously I once figured out how to fix it, but I've forgotten where I wrote it down (if at all):

23:47:36 (master *) root@go.tolidano.com:/opt/web/complimateapp/frontend/web/.well-known/acme-challenge
< ls
hi.txt
23:47:37 (master *) root@go.tolidano.com:/opt/web/complimateapp/frontend/web/.well-known/acme-challenge
< cat hi.txt
hi

You can reach this file: http://www.complimateapp.com/.well-known/acme-challenge/hi.txt

My output:

23:47:42 (master *) root@go.tolidano.com:/opt/web/complimateapp/frontend/web/.well-known/acme-challenge
< /usr/local/bin/acme-client issue --server letsencrypt --storage /etc/acme --domains www.complimateapp.com,complimateapp.com --path /opt/web/complimateapp/frontend/web --bits 4096

    Providing payload at http://www.complimateapp.com/.well-known/acme-challenge/m1xAirnWD2gTShkltK1CtS1O0mvfMR6snok-7RFtIg8
    Providing payload at http://complimateapp.com/.well-known/acme-challenge/HJ0Fxx_Kjv_Rs4zb1YxH_511uRF0q29V_hsf2fNchZM
selfVerify failed, please check http://www.complimateapp.com/.well-known/acme-challenge/m1xAirnWD2gTShkltK1CtS1O0mvfMR6snok-7RFtIg8.
selfVerify failed, please check http://complimateapp.com/.well-known/acme-challenge/HJ0Fxx_Kjv_Rs4zb1YxH_511uRF0q29V_hsf2fNchZM.
Kelunik\Acme\AcmeException: Issuance failed, not all challenges could be solved. in phar:///usr/local/bin/acme-client/src/Commands/Issue.php:104

**Comment by tolidano** [comment]
I did what you requested rafamss do above:

< ./acme issue --server letsencrypt --storage /etc/acme --domains www.complimateapp.com,complimateapp.com --path /opt/web/complimateapp/frontend/web --bits 4096

    Providing payload at http://www.complimateapp.com/.well-known/acme-challenge/OTmuH3cOTOnOfgNC_ow2hvyPH4w8K78aNgBqYZv5dxg
    Providing payload at http://complimateapp.com/.well-known/acme-challenge/huW8fwqiFLi5fWWcy0hMjRotdAUaXMQK_B3dMwmaTug
selfVerify failed, please check http://www.complimateapp.com/.well-known/acme-challenge/OTmuH3cOTOnOfgNC_ow2hvyPH4w8K78aNgBqYZv5dxg.
selfVerify failed, please check http://complimateapp.com/.well-known/acme-challenge/huW8fwqiFLi5fWWcy0hMjRotdAUaXMQK_B3dMwmaTug.
Kelunik\Acme\AcmeException: Issuance failed, not all challenges could be solved. in /home/shawn/acme/acme-client-master/src/Commands/Issue.php:106

23:55:36 shawn@go.tolidano.com:~/acme/acme-client-master/bin
> stat /opt/web/complimateapp/frontend/web/.well-known/acme-challenge/
hi.txt                                       huW8fwqiFLi5fWWcy0hMjRotdAUaXMQK_B3dMwmaTug  OTmuH3cOTOnOfgNC_ow2hvyPH4w8K78aNgBqYZv5dxg
23:55:36 shawn@go.tolidano.com:~/acme/acme-client-master/bin
> stat /opt/web/complimateapp/frontend/web/.well-known/acme-challenge/huW8fwqiFLi5fWWcy0hMjRotdAUaXMQK_B3dMwmaTug
  File: ‘/opt/web/complimateapp/frontend/web/.well-known/acme-challenge/huW8fwqiFLi5fWWcy0hMjRotdAUaXMQK_B3dMwmaTug’
  Size: 87        	Blocks: 8          IO Block: 4096   regular file
Device: ca01h/51713d	Inode: 1052619     Links: 1
Access: (0644/-rw-r--r--)  Uid: (  501/   shawn)   Gid: (  501/   shawn)
Access: 2017-06-29 23:55:36.901697390 -0400
Modify: 2017-06-29 23:55:36.901697390 -0400
Change: 2017-06-29 23:55:36.901697390 -0400
 Birth: -
23:55:56 shawn@go.tolidano.com:~/acme/acme-client-master/bin
< cat /opt/web/complimateapp/frontend/web/.well-known/acme-challenge/huW8fwqiFLi5fWWcy0hMjRotdAUaXMQK_B3dMwmaTug
huW8fwqiFLi5fWWcy0hMjRotdAUaXMQK_B3dMwmaTug.6rfRhN7xla0yvgahpG1DdZkvwY7jvklbEe6YjWDBuYQ

http://complimateapp.com/.well-known/acme-challenge/huW8fwqiFLi5fWWcy0hMjRotdAUaXMQK_B3dMwmaTug

**Comment by tolidano** [comment]
So I've found that when I curl locally, I do not receive the content - I end up with a 404.

It is properly pointing at 127.0.0.1:

< ping complimateapp.com
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=255 time=0.012 ms

But this doesn't work:

> curl http://complimateapp.com/.well-known/acme-challenge/huW8fwqiFLi5fWWcy0hMjRotdAUaXMQK_B3dMwmaTug
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /.well-known/acme-challenge/huW8fwqiFLi5fWWcy0hMjRotdAUaXMQK_B3dMwmaTug was not found on this server.</p>
</body></html>

And this doesn't work:

< curl -H "Host: complimateapp.com" http://complimateapp.com/.well-known/acme-challenge/huW8fwqiFLi5fWWcy0hMjRotdAUaXMQK_B3dMwmaTug
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /.well-known/acme-challenge/huW8fwqiFLi5fWWcy0hMjRotdAUaXMQK_B3dMwmaTug was not found on this server.</p>
</body></html>

And this isn't the normal 404 page you would get from the outside against this domain either so it doesn't appear to be hitting the right virtual host.

**Comment by tolidano** [comment]
Ok, the reason for this was that I have specific elastic IPs which I use in the VHOST config to allow multiple SSL certificates on the box but local DNS points at 127.0.0.1. Once I switched it to listen on 127.0.0.1, I now get this error instead:

< ./acme issue --server letsencrypt --storage /etc/acme --domains www.complimateapp.com,complimateapp.com --path /opt/web/complimateapp/frontend/web --bits 4096

    Providing payload at http://complimateapp.com/.well-known/acme-challenge/DDdUAQPHYLZAN6djLkMeA_poWtKwt48TUpVPeaIYkFY
    Providing payload at http://www.complimateapp.com/.well-known/acme-challenge/i1YD14nxx6F_Axi7TFIBvWO9_7sBYnP7OetABKpssRU
Challenge marked as invalid!
Challenge marked as invalid!

**Comment by tolidano** [comment]
I dumped the location from the AcmeService where this exception gets thrown, so I get this:

< ./acme issue --server letsencrypt --storage /etc/acme --domains www.complimateapp.com,complimateapp.com --path /opt/web/complimateapp/frontend/web --bits 4096

    Providing payload at http://complimateapp.com/.well-known/acme-challenge/obpb9JFsfvRd_WVnEyjkl9GMS0Xdt7vKdU8cLqoXT48
    Providing payload at http://www.complimateapp.com/.well-known/acme-challenge/Gp7iJXrcuh7Pah6zWcbFvHgHKGuPVzyJWOC4LYGUkRM
string(91) "https://acme-v01.api.letsencrypt.org/acme/authz/ND4CA71u3cht9PniTtcJnSL0u0FNVB2P-u4MEd2N6PU"
string(91) "https://acme-v01.api.letsencrypt.org/acme/authz/Wb2sQAXo_eGM8FU1FTtwJMM0l9oaPt2jruAV1AhNUy4"
string(91) "https://acme-v01.api.letsencrypt.org/acme/authz/ND4CA71u3cht9PniTtcJnSL0u0FNVB2P-u4MEd2N6PU"
string(91) "https://acme-v01.api.letsencrypt.org/acme/authz/Wb2sQAXo_eGM8FU1FTtwJMM0l9oaPt2jruAV1AhNUy4"
Challenge marked as invalid!
Challenge marked as invalid!
Kelunik\Acme\AcmeException: Issuance failed, not all challenges could be solved. in /home/shawn/acme/acme-client-master/src/Commands/Issue.php:106

For some reason, when you visit those URLs, you see it complains about admin.complimateapp.com - but that isn't one of the domains I'm trying to validate (it IS a domain, and I will have to do this process again for it, but these are the domains for this web root). Why is it doing anything with admin.complimateapp.com? (It *is* listed in my yml file [along with other domains that are not being touched right now]).

**Comment by kelunik** [comment]
> Once I switched it to listen on 127.0.0.1, I now get this error instead:

While the self verify works then, the Let's Encrypt validator will just see the error you saw before. You have to make sure it's also using the right Vhost for external requests.

**Comment by tolidano** [comment]
Makes total sense, sorry for my gaffe. Once I added the external IP back into the virtual host configuration (so it was resolving properly both locally and remotely), everything kicked in and it worked perfectly. Thanks!

**Comment by kelunik** [comment]
Closing this issue for now, glad it worked for you!
