### ISSUE TITLE
cron fatal error Undefined constant 'STDOUT'

### ISSUE THREAD

**Issue by bomakalu** [kelunik/acme-client#61]
Great work, This issue I am having is with the cron renewal: error: 

PHP Fatal error:  Undefined constant 'STDOUT' in /home/username/acme-client/vendor/league/climate/src/Util/Writer/StdOut.php on line 14

shared hosting using a cron job set up in cpanel. I cant seem to find an answer to this?

Any ideas thanks for your help:)

**Comment by kelunik** [comment]
Which PHP SAPI is this running on? What does `var_dump(PHP_SAPI);` report?

**Comment by bomakalu** [comment]
Hi there, As I am a newbie on this I am not having much luck finding these details. 
I am sorry as your script worked beautifully installing the certs.
Is there a way of determining or"Which PHP SAPI is this running on? What does var_dump(PHP_SAPI);"
I cant seem to get anything to tell me from the cli.?

**Comment by kelunik** [comment]
You can just create a new `test.php` with the following contents and run it as cron and look at the output.

```php
<?php

var_dump(PHP_SAPI);
```

**Comment by bomakalu** [comment]
hi there 
i created the file and then ran it in my browser and got
string(9) "litespeed"
is this of use?
thanks again

**Comment by kelunik** [comment]
If you access it from a browser it's probably another PHP SAPI. You really need to run it just like you ran the original script that failed.

**Comment by bomakalu** [comment]
ok 
When i create the cron from cpanel I am using this:

To renew certificate, customer can set up cron job as under every month :
===================================
php acme-client/bin/acme issue --domains domain.com:www.domain.com --path /home/username/public_html:/home/username/public_html --server letsencrypt
===================================

i created the test.php and then ran this as a cron:

/usr/local/bin/php /home/petehillman/public_html/test.php

i set it for everyminute but its not sending anything through or i am not seeing output?
thanks

**Comment by kelunik** [comment]
Maybe you only get the error output? Then try `fputs(fopen("php://stderr"), PHP_SAPI);`

**Comment by bomakalu** [comment]
Hi there 
I a dont understand this you mean as replace the test.php with this code?
thanks

**Comment by bomakalu** [comment]
Ok heres the cron email i just got:

Status: 500 Internal Server Error
X-Powered-By: PHP/5.6.30
Content-type: text/html; charset=UTF-8

**Comment by kelunik** [comment]
I guess your cron just calls the webserver and runs it. Is your acme-client installation accessible via the web browser?

**Comment by bomakalu** [comment]
I cant access that location via the webbrowser. 
it looks like the cron for some reason using cpanel wont run this from the correct 
location. Is there a way to run this from the cli and create an auto renew?
thanks

**Comment by kelunik** [comment]
I don't know. Could you ask your hosting provider regarding that?

**Comment by bomakalu** [comment]
I have been on hold with them for almost a day. the issue i have is to just get it to renew on auto and there cron wont do it. what about manual renew is that simple?
thanks

**Comment by kelunik** [comment]
You can also simply run `acme-client issue` every month, but your hosting provider really should run the cron with `php-cli` instead of any other PHP SAPI.

**Comment by bomakalu** [comment]
This is great help I am very thankful spent a ,ot of head scratching as its a crapy server and they are as helpful as a dead cat. I will try it and get back to you. thanks for your help

**Comment by kelunik** [comment]
You could just add the following code at the beginning of `bin/acme` for now: https://stackoverflow.com/a/28898174/2373138

**Comment by bomakalu** [comment]
Hi there
brilliant 
so when i added them i get this error via email:

Please run this script on the command line!
X-Powered-By: PHP/5.6.30
Content-type: text/html; charset=UTF-8

Does thsi mean anything? 

thanks

**Comment by kelunik** [comment]
You can either remove the check or add your `PHP_SAPI` for now.

https://github.com/kelunik/acme-client/blob/f4cabf755b0615ef1e33a0efbbfdeb2a8081cc33/bin/acme#L78-L81

**Comment by bomakalu** [comment]
Hello and thanks
Can you say more about this: "add your PHP_SAPI for now." 
I appreciate your help
thanks again

**Comment by kelunik** [comment]
The thing you previously got from `fputs(fopen("php://stderr"), PHP_SAPI);`, but just remove the check.

**Comment by bomakalu** [comment]
Hi there I ran the issue at the command line and received this error:

selfVerify failed, please check http://www.petehillman.com/.well-known/acme-challenge/EoI-fBRTnai3OBQtw5_3j5LfHV__gN0_XdI4uMlxanM.
exception 'Kelunik\Acme\AcmeException' with message 'Issuance failed, not all challenges could be solved.' in /home/petehillman/acme-client/src/Commands/Issue.php:106

are you familiar with this?

thanks

**Comment by bomakalu** [comment]
I see from another thread "I had the same problem, it drove me nuts for a whole day. Turned out I had set up .htaccess to allow access only from my IP. Don't know if this is issue in your case, but it's one thing you might check. I don't know what IP is acme-client using, but looking at logs I see that now it was 66.133.109.36." 

I can see I will continue to get this error. Do you know of a way to allow the acme-client access via the htaccess file.
thanks mate its a head scratcher

**Comment by kelunik** [comment]
You need to allow public access, not only for acme-client, as the CA (Let's Encrypt) needs access, too.
