### ISSUE TITLE
Is Reneval command implemented

### ISSUE THREAD

**Issue by mateuszjarzewski** [kelunik/acme-client#66]
There is a limit for issued certs (20 per week per domain).
I wonder if renewal function is something else (implemented separately) than issue function.
Cuz if it's the same function, then renevals will affect this limit...
Or maybe I have everything backwards.
This will become not a problem at all in Jan 2018 when they start offering wildcard-certs.

**Comment by kelunik** [comment]
There's a `check` command that determines whether you need a new certificate. Generally, you should probably use the `auto` command, that handles that automatically.

**Comment by kelunik** [comment]
I guess this has been answered. If not, just respond with further questions. :+1:

**Comment by ghost** [comment]
I know this is closed, but how do I renew? I tried the auto command but it is asking for a config file... where is this stored?

**Comment by kelunik** [comment]
@ZapTechAdmin Please read the documentation. https://github.com/kelunik/acme-client/blob/d4f20093150579ea6c5d7e790857bad77d7b3bf5/doc/usage.md#configuration

**Comment by ghost** [comment]
I tried that but it returned an error
```
    No private key found, generating new one ...
Amp\File\FilesystemException: Couldn't create key directory: '/acme-client/certs/accounts' in /home/u492836762/acme-client/src/Stores/KeyStore.php:50

Next Kelunik\AcmeClient\Stores\KeyStoreException: Could not save key: Couldn't create key directory: '/acme-client/certs/accounts' in /home/u492836762/acme-client/src/Stores/KeyStore.php:57
```

**Comment by kelunik** [comment]
What's your config?
