### ISSUE TITLE
acme-client issue hangs after authorization

### ISSUE THREAD

**Issue by tturnerdev** [kelunik/acme-client#68]
`acme-client issue` seems to hang on issuing cert step at some point.

I've only had one or or maybe two certs successfully issued, so I don't think I'm being rate limited?
(I confirmed this via `https://crt.sh/?Identity=%25MYDOMAIN.com&iCAID=16418`, shows only 1 recently issued)
In any case, I get no error output, the client just seems to hang.

Originally, I was able to successfully get one cert for `mydomain.com` and `www.mydomain.com`.
However, since then I've been unable to get a new cert, for any new / different domain.

I've read some posts from other users having networking problems (routing, dns, firewall, etc).
Their symptoms seem to be the same as mine, however their situation was different.
So I suspect there is some network issue (see below for network output from environment).
**I notice I get no response via PING...** (again, see below, networking)
cURL request works fine most of the time, I did notice it hangs sometimes as well (maybe on trying to select correct enc type for connection?)

However, I'm unable to troubleshoot or diagnose any further, as I'm not sure where else to look.
Any assistance / suggestions would be greatly appreciated!

Setup works fine:
```
$ acme-client setup --email MYEMAIL@MYCOMPANY.com
Using existing private key ...
Registering with acme-staging.api.letsencrypt.org/directory ...
Registration successful. Contacts: mailto:MYEMAIL@MYCOMPANY.com
```

Using `$ acme-client auto` command results in no output (probably hangs in same spot)

Using `issue` command directly:
```
$ acme-client issue -d MYDOMAIN.com:www.MYDOMAIN.com -p /home/USER/MYDOMAIN.com
    Providing payload at http://MYDOMAIN.com/.well-known/acme-challenge/asdfasdfasdfCHALLENGECODE
    MYDOMAIN.com is now authorized.

```

Using `issue` command directly, with staging server:
```
$ acme-client issue -d MYDOMAIN.com:www.MYDOMAIN.com -p /home/USER/MYDOMAIN.com
    Providing payload at http://MYDOMAIN.com/.well-known/acme-challenge/asdfasdfasdfCHALLENGECODE_SAME_AS_RETURNED_BY_NON_STAGING_SERVER
    MYDOMAIN.com is now authorized.

```
_Please note: in both cases the output hangs on newline after authorized output._

**Environment**
cPanel (Shared Hosting),
```
$ uname -a
Linux hostname 2.6.32-773.26.1.lve1.4.46.el6.x86_64 #1 SMP Tue Dec 5 18:55:41 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
```
PHP Versions available (tried with php56, php70, php71):
```
$ php -v
PHP 7.0.22 (cli) (built: Aug 30 2017 09:24:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.0.9, Copyright (c) 2002-2016, by ionCube Ltd.
```

```
$ /opt/php56/bin/php -v
PHP 5.6.31 (cli) (built: Jul 13 2017 12:42:45)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.1.1, Copyright (c) 2002-2016, by ionCube Ltd.
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies
```

```
$ /opt/php71/bin/php -v
PHP 7.1.7 (cli) (built: Jul 17 2017 08:47:06) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```
```
$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
```
PHP with openssl support:
```
$ php -i | grep -i OPENSSL
Configure Command =>  './configure' ... '--with-openssl' ...

SSL Version => OpenSSL/1.0.1e
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL Header Version => OpenSSL 1.0.1e-fips 11 Feb 2013
Openssl default config => /etc/pki/tls/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
Native OpenSSL support => enabled
```

```
$ curl --version
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
```

**Networking Results**
Maybe CDN issue? No clue, but I get no response....
```
$ ping !$
ping acme-staging.api.letsencrypt.org
PING e981.dscb.akamaiedge.net (23.196.212.53) 56(84) bytes of data.

```
```
$ ping 23.196.212.53
PING 23.196.212.53 (23.196.212.53) 56(84) bytes of data.
```

```
$ traceroute acme-staging.api.letsencrypt.org
traceroute to acme-staging.api.letsencrypt.org (23.196.212.53), 30 hops max, 60 byte packets
 1  256.256.256.256 (256.256.256.256)  0.184 ms  0.172 ms  0.178 ms
 2  * * *
 3  lag-151.ear2.LosAngeles1.Level3.net (4.71.136.1)  0.484 ms *  0.711 ms
 4  * * *
 5  * * *
```

cURL seems to work just fine when contacting the host...
```
$ curl -v https://acme-v01.api.letsencrypt.org/directory
* About to connect() to acme-v01.api.letsencrypt.org port 443 (#0)
*   Trying 23.196.212.53... connected
* Connected to acme-v01.api.letsencrypt.org (23.196.212.53) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: C=US,ST=California,L=Mountain View,O=INTERNET SECURITY RESEARCH GROUP,CN=*.api.letsencrypt.org
*       start date: Jun 26 17:05:45 2015 GMT
*       expire date: Jun 25 17:05:45 2018 GMT
*       common name: *.api.letsencrypt.org
*       issuer: CN=TrustID Server CA A52,OU=TrustID Server,O=IdenTrust,C=US
> GET /directory HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: acme-v01.api.letsencrypt.org
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: application/json
< Content-Length: 562
< Replay-Nonce: pmBWMasdfasdfasdfasdfafsdsadfk8
< X-Frame-Options: DENY
< Strict-Transport-Security: max-age=604800
< Expires: Mon, 18 Dec 2017 20:45:19 GMT
< Cache-Control: max-age=0, no-cache, no-store
< Pragma: no-cache
< Date: Mon, 18 Dec 2017 20:45:19 GMT
< Connection: keep-alive
<
{
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "ln0cfclsAeI": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "meta": {
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
* Connection #0 to host acme-v01.api.letsencrypt.org left intact
* Closing connection #0
```

When cURL hangs, it does so reight before the `* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` line displayed in successful connections:
```
$ curl -v https://acme-v01.api.letsencrypt.org/directory
* About to connect() to acme-v01.api.letsencrypt.org port 443 (#0)
*   Trying 23.196.212.53... connected
* Connected to acme-v01.api.letsencrypt.org (23.196.212.53) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none

```

**Comment by Ayesh** [comment]
Default storage location for certificates is `/etc/acme`, where I don't think shared hosts allow access to. In Registering a personal key would also require access to the same directory though. 
Perhaps you can try with a different storage location (with `--storage ~/acme` for example)?

**Comment by tturnerdev** [comment]
Thanks for the quick reply, I really appreciate it!

My apologies I completely forgot to include config, this an obvious omission, my bad!
Yes, I tested with `--storage` option and also added to config.
And, I see the keys generated as well, so I know the setup part works just fine.

**Comment by tturnerdev** [comment]
Also, just as additional troubleshooting info, it does seem more likely this is due to some sort of SSL handshake lag or strangeness.

Testing with a few other clients, the script hangs several times in the similar spot (requesting cert).
For example, in this script I had to re-run the client 4 times (ctrl+c at hang and immediately running again) before the client would get further through the process:

```
$ acme.sh --issue -d mydomin.com -d www.mydomin.com -w /home/USER/mydomin.com
[Mon Dec 18 13:42:57 PST 2017] Registering account
^C
[USER@res192 acme_sh]$ acme.sh --issue -d mydomin.com -d www.mydomin.com -w /home/USER/mydomin.com
[Mon Dec 18 13:43:22 PST 2017] Registering account
^C
[USER@res192 acme_sh]$ acme.sh --issue -d mydomin.com -d www.mydomin.com -w /home/USER/mydomin.com
[Mon Dec 18 13:43:25 PST 2017] Registering account
[Mon Dec 18 13:43:26 PST 2017] Registered
[Mon Dec 18 13:43:26 PST 2017] ACCOUNT_THUMBPRINT='5L9g7EXwQXke93OMIfp77_aEX8Y6QR_O41T6LoftTKI'
[Mon Dec 18 13:43:26 PST 2017] Creating domain key
[Mon Dec 18 13:43:26 PST 2017] The domain key is here: /home/USER/.acme.sh/mydomin.com/mydomin.com.key
[Mon Dec 18 13:43:26 PST 2017] Multi domain='DNS:www.mydomin.com'
[Mon Dec 18 13:43:26 PST 2017] Getting domain auth token for each domain
[Mon Dec 18 13:43:26 PST 2017] Getting webroot for domain='mydomin.com'
[Mon Dec 18 13:43:26 PST 2017] Getting new-authz for domain='mydomin.com'
[Mon Dec 18 13:48:27 PST 2017] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Mon Dec 18 13:48:27 PST 2017] The new-authz request is ok.
[Mon Dec 18 13:48:27 PST 2017] Error, can not get domain token mydomin.com
[Mon Dec 18 13:48:27 PST 2017] Please add '--debug' or '--log' to check more details.
[Mon Dec 18 13:48:27 PST 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```

I realize my openssl version is pretty old, so maybe there's something causing trouble there...

**Comment by tturnerdev** [comment]
On another client, via `--debug`, I see what appear to be several cURL timeouts:

```
[Mon Dec 18 13:54:51 PST 2017] _CURL='curl -L --silent --dump-header /home/USER/.acme.sh/http.header '
[Mon Dec 18 13:54:51 PST 2017] _ret='0'
[Mon Dec 18 13:54:51 PST 2017] code='202'
[Mon Dec 18 13:54:52 PST 2017] sleep 2 secs to verify
[Mon Dec 18 13:54:54 PST 2017] checking
[Mon Dec 18 13:54:54 PST 2017] GET
[Mon Dec 18 13:54:54 PST 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/MbU6KoBl94VrXxWgTFqXat-Olp8IamhQdfSy-RAF70I/2788557046'
[Mon Dec 18 13:54:54 PST 2017] timeout
```

**Comment by Ayesh** [comment]
~~You seem to be using [acme.sh](https://github.com/Neilpang/acme.sh) and not this client. This one is `acme-client`, written with PHP.~~
Sorry.

**Comment by tturnerdev** [comment]
I tried to say a couple times I was only testing with a few other clients to see if it was this client having the issue or a lower level (curl, openssl, etc) problem.

acme.sh was being used for it's more verbose output in the connection to see exactly where the connection was failing.

There's a very good chance this client itself is not the problem, and indeed it might be a lower level cause.

**Comment by tturnerdev** [comment]
Yeah, I'm leaning heavily towards some inconsistency with cURL / SSL and timeouts.

For example the `acme.sh` client keeps hanging after different, arbitrary number of requests.
Sometimes its after 3 requests, sometimes after 6, etc.

So most likely this is not related to the client, so I'll plan on closing this issue if I don't figure out a solution soon, since my issue is probably out of scope for the client...

Thanks again, I appreciate the help and quick response!

**Comment by Ayesh** [comment]
Yeah sorry I misread. 
I'm not the maintainer of this client, just someone who uses it a lot. Perhaps maintainer @kelunik can shed some light?

**Comment by tturnerdev** [comment]
Hmm this might be related:

> Your domain has both ipv6 and ipv4 resolved, but your server is only listening at ipv4.
> 
> The letsencrypt CA is connecting to the ipv6 address, so it gets a timeout.
> please remove your AAAA record of your domain.
> 
>  "addressesResolved": [
>         "188.226.136.31",
>         "2a03:b0c0:0:1010::c6:f001"
>       ],
>       "addressUsed": "2a03:b0c0:0:1010::c6:f001",
>       "addressesTried": []

Indeed, I did notice from another server I got:
```
ping acme-staging.api.letsencrypt.org
PING acme-staging.api.letsencrypt.org(2001:559:19:28a1::3d5 (2001:559:19:28a1::3d5)) 56 data bytes
64 bytes from 2001:559:19:28a1::3d5 (2001:559:19:28a1::3d5): icmp_seq=1 ttl=61 time=11.4 ms
^C
--- acme-staging.api.letsencrypt.org ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 11.417/11.417/11.417/0.000 ms
```

**Comment by tturnerdev** [comment]
Ah yeah, confirmed my shared hosting provider doesn't have ipv6 setup, what a joke!

I'll confirm this is the real issue and then close this out.

**Comment by Ayesh** [comment]
That's a pretty clever observation. Sad to see it's almost the end of 2017 and some shared hosts don't support ipv6 yet.

**Comment by kelunik** [comment]
@ronindesign From which client did you get the above hint? I guess we could implement a check for such a situation.

**Comment by tturnerdev** [comment]
Hi @kelunik, thanks for the response, I appreciate it.

Also, just to confirm, there is no issue with this library, I pulled to another system and made same requests without problem.
So it really must be some issue with the first server's environment / config.
I'm still not certain if it is ipv4/6 related or if it's just multiple curl requests not being handled correctly.
In any case, this is probably a ~~cURL~~ request issue, at the highest level, but also possible a lower network / routing level issue.

**To answer your question:**
I initially was able to discover there was trouble when viewing the cURL requests (timeouts) using the `--debug` option in the client [acme.sh](https://github.com/Neilpang/acme.sh).
Let me know if I can provide any additional info for my use case.

**Comment by tturnerdev** [comment]
Also, as a side note, since I've been unable to implement this on the target host, I'll probably end up doing some sort of remote request / auth at the target server.

For now I'm testing with this client and using sshfs (fuse filesystem) to simulate the remote directory as a local directory (and set `storage` there).

If you happen to have any insight or know of a "usual" way to do this, I'd appreciate any suggestions.
None of the acme clients I've seen really support a remote target host, from what I can tell...
If it's worth the effort I can always fork and add in the functionality if it makes sense.

**Comment by kelunik** [comment]
It's not a cURL issue, but rather something else, as we don't use cURL. But if it hangs with cURL just as with this client, that's a good sign. It means it's also not our DNS component.

I guess we could just add another `ChallengeStore` that uses `scp` or so to upload challenge files to the remote? ... which might not be available for such shared hosts. Which transfer possibilities do you have?

**Comment by tturnerdev** [comment]
Ah, right of course, my mistake, I was meaning the request mechanism in general, but stated cURL.
I also found it strange that I was not even able to ping the server.
I found mentions of Let's Encrypt's CDN servers acting strangely, but nothing concrete.

Scp would be fantastic! Currently this is what I'm mimicing vis sshfs.
For example:
`sshfs user@myserver.com:/home/user/ /home/localuser/remoteuser`
I would then use the client to write to ~/remoteuser/, such as:
`~/remoteuser/mydomain.com/public_html` for a domain
`~/remoteuser/acme-client/storage` for certs

Then I'm planning on using simple cPanel API client [sslic](https://github.com/neurobin/sslic/) to install certs directly into cPanel/WHM.

If I understand `scp` well enough, it uses same access as `ssh`, e.g. if you have ssh access you'll also be able to use scp?
In my experience so far, all my shared hosting providers have ssh access available.
While the capabilities available in those ssh environments varies, ssh and transfer via scp have always been available (at least in my personal experience).

So I'm thinking `scp` would be a great method for uploading if that works.
Other options might be `sftp`, but again, if that's an option, `scp` probably will be a well...

**Comment by tturnerdev** [comment]
Also, in regards to the step of installing certs, I think one of the following is needed:
1) Remote `CertificateStore` using `scp` similar to discussed `ChallengeStore`, or
2) A way to target remote hosts for cert install, using locally stored certs (i.e. not on the target cPanel/WHM server), this would probably be out of scope for this client though.

The first would be more ideal, as it would keep everything collected on the target, close to the area of concern.
Otherwise, my "task" remote host ends up storing several directories for each (shared hosting) target host, creating a strange dependance I think...

**Comment by tturnerdev** [comment]
So after some days, I can now once again ping `acme-v01` (via their CDN `e981.dscb.akamaiedge.net (23.196.212.53)`)

So I believe this entire issue was intermittent and network related.

Closing this for now, but since the idea of remote `ChallengeStore`, `CertificateStore` might be useful, I'll create a different issue as a feature request.

Thanks for your attention and assistance on this issue, I appreciate it!
