### ISSUE TITLE
syntax error /bin/acme

### ISSUE THREAD

**Issue by akira187** [kelunik/acme-client#71]
PHP Parse error:  syntax error, unexpected '$command' (T_VARIABLE) in /home/suchilsa/acme-client/bin/acme on line 165

**Comment by kelunik** [comment]
Which version of PHP are you using? And which version of the client?

**Comment by akira187** [comment]
I am using PHP 5.6 and client ver 0.3.0 alpha3

**Comment by kelunik** [comment]
You need PHP version 7.0+ for version 0.3.0.

**Comment by ojovent** [comment]
@kelunik why we need php version 7.0+. You wrote PHP 5.5+ with OpenSSL In your documentation?

**Comment by kelunik** [comment]
@ojovent PHP 5.5 is true for the latest stable release, but not for the current master.

**Comment by ojovent** [comment]
@kelunik I want to use your repo but i don't understand, which release works with php 5.6? Your all branches contains yield (run with php 7).

**Comment by kelunik** [comment]
@ojovent Every 0.2.x release, e.g. https://github.com/kelunik/acme-client/tree/v0.2.14. `yield` is available as of PHP 5.5.
