### ISSUE TITLE
Windows: The system cannot find the path specified.

### ISSUE THREAD

**Issue by ghost** [kelunik/acme-client#72]
I tried passing in the .acme-client.yml configuration on Windows and it says "The system cannot find the path specified."  The paths look like for Unix but how do you specify the path for Windows based file system

ex:
/var/www/home

vs.
C:\var\www\home 

It's not able to find the file path

also checked the /etc/acme for the client and it doesn't seem like its finding it.

**Comment by Globulopolis** [comment]
From docs:

> The client takes the first available of ./acme-client.yml (if running as PHAR)

So, if you running command like this `php acme.phar ...` client will search config file automatically. `./` mean `from current path`.

Just place .phar, .yml in same folder and run command.
