### ISSUE TITLE
Additional cert information like OU, Country etc.

### ISSUE THREAD

**Issue by FabulousGee** [kelunik/acme-client#73]
First of all: my client is working just fine in the current setup. It seems to be all correct and I get a working certificate.
But when I was importing it lately to another application, I noted that there is some properties missing. The missing props are:
Organization
Organizational Unit
Country / Region
State / Province
City / locality

Did I miss to fill these out on initial create or is this not supported yet?
How can I add these now (afterwards) without a hassle?

Thanks for any help

**Comment by Globulopolis** [comment]
This information available only for EV certs. If you submit additional information in CSR for DV cert the issuer will ignore these fields.

**Comment by kelunik** [comment]
For this information to be present in a certificate, you need organization validation (OV), while Let's Encrypt only supports domain validation (DV).
