### ISSUE TITLE
Support for acme v2?

### ISSUE THREAD

**Issue by AkashKrx** [kelunik/acme-client#74]
https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

Does this repo support wild card?

**Comment by kelunik** [comment]
Not yet, see https://github.com/kelunik/acme/issues/31.

**Comment by AkashKrx** [comment]
Well then looking forward for its support.

**Comment by FabulousGee** [comment]
This would be an awesome new feature.
+1

**Comment by IOAyman** [comment]
Looking forward to it! :+1:

**Comment by pgporada** [comment]
Clients that do not support ACMEv2 will be de-listed from the clients page per https://github.com/letsencrypt/website/pull/761.

**Comment by kenrick95** [comment]
The support for ACME v2 is getting more and more urgent now.

ACME v1 support will be dropped eventually. Starting in June 2020, they will stop "allowing new domains to validate via ACME v1"

https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1

**Comment by kelunik** [comment]
Acme v2 is now supported in 1.0.0 Beta 1.
