### ISSUE TITLE
Auto command use single time only or need to fire cron every day?

### ISSUE THREAD

**Issue by khushangmbhavnagarwala** [kelunik/acme-client#76]
Hello Kelunik,

@kelunik @spikyjt 

I have generate a SSL certificate using acme-client on LetsEncrypt.

Can you please answer my question as I am little bit confuse in this?

1. At first time I have create certificate for single single domain by executing "acme-client.phar auto" and after that for renewal of certificate, should I need execute cron daily? 

2. "acme-client.phar auto" will checks the domain that it needs renewal or not. If it needs renewal then domain will get renew by cron and if it not then cron will do nothing. Correct?

3. Domain expiry period is 90 days but "acme-client.phar auto" command renews domains on 60 days? Correct me if I am wrong?

And awesome script made for generating SSL.

Thank you so much.

**Comment by PeeHaa** [comment]
Yes to all of the above: https://github.com/kelunik/acme-client/blob/master/doc/usage.md#certificate-issuance

**Comment by kelunik** [comment]
As @PeeHaa already said, yes to all of above. :)
