### ISSUE TITLE
Change email account

### ISSUE THREAD

**Issue by niuso** [kelunik/acme-client#78]
Hello, I need to change the email with what I registered the certificate in let's encrypt
Does this have this function?
If that is not possible, do I have to make a new registration with a new email and retrieve a new certificate for my domain?
Thank you

**Comment by kelunik** [comment]
You should be able to execute [`acme-client setup --email me@example.com
`](https://github.com/kelunik/acme-client/blob/master/doc/advanced-usage.md#register-an-account) to change the email address while leaving the currently used key intact. Maybe it also works if you just change the email in the config and run `acme-client auto`, but not sure.

**Comment by niuso** [comment]
it does not work
`php acme-client/bin/acme setup --email newemail@newemail.com`

This is just what he tells me.

`php acme-client/bin/acme setup --email newemail@newemail.com
_Usage: bin/acme setup [--email email] [-s server, --server server] [--storage st                                  orage (default: /home/myuser/acme-client/data)]

Required Arguments:
        -s server, --server server
                ACME server to use for registration and issuance of certificates                                  .
        --email email
                E-mail for important issues, will be sent to the ACME server.

Optional Arguments:
        --storage storage (default: /home/myuser/acme-client/data)
                Storage directory for account keys and certificates.

The following arguments are required: [-s server, --server server]._`


If I add --server, then it's like making a new account. 
This is what I did to register in letsencrypt `php bin/acme setup --server letsencrypt --email myemail@myemail.com`
Can I generate a new account with the new mail and a new certificate from the same domain again?

Thank you.

**Comment by kelunik** [comment]
You can also generate a new account, yes. But if the data directory is the same (which it should be), then it will update the existing account. You'll just need to add `--server` and not delete the old key.

**Comment by niuso** [comment]
Then a new account but leaving the old certificates. 
`php bin/acme setup --server letsencrypt --email mynewemail@mynewemail.com`
Will let´s encrypt associate this new account with the old certificates?
Will Let´s encrypter send me messages to the new mail when the old certificate expires?
Thanks

**Comment by p0limorf** [comment]
Hi!
I try to register
`php bin/acme setup -s letsencrypt --email myemail@gmail.com`
but I get this error:
`InvalidArgumentException: Label 'gmail' could not be processed for IDN in /opt/share/nginx/mydomainname/acme-client/vendor/daverandom/libdns/src/functions.php:9`

What am I doing wrong?
p.s. PHP 7.2.5-2

**Comment by kelunik** [comment]
@p0limorf Thanks for reporting, I'll try to look into it. If you don't hear back in the coming days, please re-ping me.

**Comment by p0limorf** [comment]
> @p0limorf Thanks for reporting, I'll try to look into it. If you don't hear back in the coming days, please re-ping me.

Problem is not solved?

**Comment by kelunik** [comment]
@p0limorf What's the version of PHP, `ext-intl`, and `libicu` on your system?
