### ISSUE TITLE
Error Delete folder acmet-client

### ISSUE THREAD

**Issue by niuso** [kelunik/acme-client#79]
After doing several installations, I try to delete the old acme-client folders. I renamed them to make a new installation but now I want to delete them.
I scan even the folders but there are no files. I have activated "force hidden files"(filezilla, winscp)
Also using ssh connection I use `rmdir folder_name` and the same error.
Thank you.

**Comment by kelunik** [comment]
What's the error you're seeing? Seems to be a hosting / system administration issue and not really caused by this software, so I'm closing this issue.
