### ISSUE TITLE
syntax error with bin/acme

### ISSUE THREAD

**Issue by 01micko** [kelunik/acme-client#80]
I followed a tutorial [here](https://www.hostinger.com/tutorials/ssl/how-to-install-free-ssl-from-lets-encypt-on-shared-hosting) to see if I could install a certificate on my shared hosting. I am not using hostinger.

It went fine until I tried to register. here is the cli dump from my ssh session:

```
mickocom@webcloud26 [~/acme-client]# php bin/acme setup --server letsencrypt --email 01micko@gmail.com
mickocom@webcloud26 [~/acme-client]# cat error_log 
[18-Jul-2018 06:18:33 UTC] PHP Parse error:  syntax error, unexpected '$command' (T_VARIABLE) in /home/mickocom/acme-client/bin/acme on line 160
[18-Jul-2018 06:18:46 UTC] PHP Parse error:  syntax error, unexpected '$command' (T_VARIABLE) in /home/mickocom/acme-client/bin/acme on line 160
[18-Jul-2018 06:26:02 UTC] PHP Parse error:  syntax error, unexpected '$command' (T_VARIABLE) in /home/mickocom/acme-client/bin/acme on line 160
mickocom@webcloud26 [~/acme-client]# php -v
ea-php-cli Copyright 2017 cPanel, Inc.
PHP 5.6.36 (cli) (built: May 11 2018 12:21:59) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
mickocom@webcloud26 [~/acme-client]#
```

I spent a few minutes trying to debug myself but I am pretty much a beginner with php.

Thanks for any advice.

**Comment by 01micko** [comment]
BTW, I tried the recommended way using the .phar but the error is identical except it is on line 159.

```
[18-Jul-2018 07:09:58 UTC] PHP Parse error:  syntax error, unexpected '$command' (T_VARIABLE) in phar:///home/mickocom/acme/acme-client.phar/bin/acme on line 159
```

EDIT: produces the same error on my local machine, running php-5.6.36

**Comment by kelunik** [comment]
Which version did you use?

**Comment by 01micko** [comment]
The latest release 0.3.0 beta 4

**Comment by kelunik** [comment]
0.3.x requires PHP 7.0 or greater, so you'll either need to upgrade or use 0.2.x

**Comment by 01micko** [comment]
ok thanks. I'll try 0.2 later.

**Comment by 01micko** [comment]
looks like I'm out of luck. Tried the last few 0.2x versions of the phar and no luck.

Error follows..

```
mickocom@webcloud26 [~/acme]# php acme-client.phar setup --server letsencrypt --email 01micko@gmail.com --storage /etc/acme

    No private key found, generating new one ...
exception 'Kelunik\AcmeClient\Stores\KeyStoreException' with message 'Could not create key store directory.' in phar:///home/mickocom/acme/acme-client.phar/src/Stores/KeyStore.php:74
```

Thanks anyway.. maybe I'll change hosting to one that supports Let's Encrypt.

**Comment by kelunik** [comment]
You won't have any rights to modify /etc/acme on shared hosting, so you need to choose another directory.

**Comment by 01micko** [comment]
Ah of course so I now use `~/etc/acme` and we are away . I'll let you know if I can actually setup the https:// on my site and maybe write a tutorial on my blog if it works out ok.

Thank you very much!

**Comment by kelunik** [comment]
I'm glad it works. :-)
