### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '$command' (T_VARIABLE) in /path/to/bin/acme on line 160

### ISSUE THREAD

**Issue by shaktee** [kelunik/acme-client#81]
Running this on a wordpress installation, and install went fine.

When I run bin/acme, I get this in the error_log

`[15-Oct-2018 14:54:21 America/New_York] PHP Parse error:  syntax error, unexpected '$command' (T_VARIABLE) in /path/to/acme-client/bin/acme on line 160
`
My PHP version is

```
php --version
PHP 5.6.38 (cli) (built: Sep 14 2018 02:23:55) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

```

Offending line is the one with $command

```
    try {
        $exitCode = yield $command->execute($climate->arguments);

        if ($exitCode === null) {
            $exitCode = 0;
        }

```

**Comment by shaktee** [comment]
I know the PHP version is older than supported, but my problem is that it does not even execute

```
if (PHP_VERSION_ID < 70000) {
    $climate->yellow("You're using an older version of PHP which is no longer supported by this client. Have a look at http://php.net/supported-versions.php and upgrade at least to PHP 7.0!");
}
```

**Comment by kelunik** [comment]
If you use PHP 5, you need to use the 0.2.x release series. The warning is dead code in the newer versions, because they require PHP 7.

**Comment by shaktee** [comment]
Thank you. I see a 0.1.x branch and a master, but no 0.2.x. I was on master.

```
$ git checkout 0.2.x
error: pathspec '0.2.x' did not match any file(s) known to git.
$ git rev-parse --abbrev-ref HEAD
master

```

Where is the 0.2.x code?

**Comment by kelunik** [comment]
I probably forgot to make a branch, so just use the releases that are provided.
