### ISSUE TITLE
Update with installation composer.

### ISSUE THREAD

**Issue by niuso** [kelunik/acme-client#82]
Hi, I have an installation with composer.
git clone https://github.com/kelunik/acme-client && cd acme-client
composer install

How do I update acme-client to a new version?
If I reinstall, it says busy folder and forces me to delete everything. Also I do not want to reinstall, delete certified folders and stop working for a few minutes.

Thank you.

**Comment by kelunik** [comment]
You can update by executing `git pull; composer install`. Maybe it's easier switching to the provided `.phar` archives in the release section as installation method.
