### ISSUE TITLE
Kelunik\Acme\AcmeException: Verification failed, please check the response body for

### ISSUE THREAD

**Issue by ballinc** [kelunik/acme-client#83]
Hi there,

I have been trying to follow the [Hostinger tutorial](https://www.hostinger.co.uk/tutorials/ssl/how-to-install-free-ssl-from-lets-encypt-on-shared-hosting#gref) for lets encrypt ssl. (I am using it for Ionos shared hosting (ex-1and1).

However I get the error:

`Kelunik\Acme\AcmeException: Verification failed, please check the response body for 'http://tekman03.co.uk/.well-known/acme-challenge/NfL29L2G0fRL_GtKH0nz5cESgMd1B2EiwZtFfKWOh4s'. It contains '' but 'NfL29L2G0fRL_GtKH0nz5cESgMd1B2EiwZtFfKWOh4s.N_gzS9x0KzAAdIQ9kgCjNmv6X11k2YbMxS5oMimm2WU' was expected. in /homepages/23/d723843075/htdocs/acme-client/vendor/kelunik/acme/lib/Verifiers/Http01.php:62
`

After reading other issues I have stopped it deleting the file and [the page](http://tekman03.co.uk/.well-known/acme-challenge/NfL29L2G0fRL_GtKH0nz5cESgMd1B2EiwZtFfKWOh4s) doesn't load.

@kelunik has said in previous issues that there may be a problem with the config but never actually explains what the problem is or how to fix it...

Any help would be greatly appreciated.

**Comment by kelunik** [comment]
Some webservers are configured, so they don't serve any files or directories starting with a dot. If you haven't done this via an .htaccess file or something, you probably have to ask your hoster to add an exclusion for .well-known/acme-challenge.

**Comment by OZ-Nerol** [comment]
I have faced the **exact** same problem today.

Run the 'Fix File Ownership' feature (https://support.hostinger.com/hpanel/how-can-i-fix-permissions-of-my-files).

Then re-run
`php bin/acme issue --domains yourdomain.com:www.youdomain.com --path /home/x123011738/public_html:/home/x123011738/public_html --server letsencrypt`

and all should be good. Worked for me.

**Comment by ballinc** [comment]
Unfortunately I’ve probably not been clear enough in saying that I used the Hostinger tutorial but for IONOS (1and1) hosting. :(

**Comment by kelunik** [comment]
If you can't figure it out, I'd create a file at `
http://tekman03.co.uk/.well-known/acme-challenge/NfL29L2G0fRL_GtKH0nz5cESgMd1B2EiwZtFfKWOh4s` manually and try to access it from your browser. If it doesn't work, maybe their support can assist you?

**Comment by ballinc** [comment]
It doesn't seem to load any page, even a txt.

That's probably the best idea, however I suspect that they will try to make me buy their one....

Thanks for your help

**Comment by kelunik** [comment]
I'll close this one then, good luck!

**Comment by raibis** [comment]
I have faced identical issue today.

You have to modify path, if you have multiple domains on the same account to solve the issue.

php bin/acme issue --domains yourdomain.com:www.yourdomain.com --path /home/x123011738/domains/yourdomain.com/public_html:/home/x123011738/domains/yourdomain.com/public_html --server letsencrypt
