### ISSUE TITLE
PHP Fatal error on any command except help and version.

### ISSUE THREAD

**Issue by Tumbler** [kelunik/acme-client#84]
Every command except help and version give me this error:

> PHP Fatal error:  Uncaught Error: Call to undefined function League\CLImate\Argument\mb_strstr() in phar://C:/PHP7/acme-client.phar/vendor/league/climate/src/Argument/Summary.php:124
> Stack trace:
> #0 phar://C:/PHP7/acme-client.phar/vendor/league/climate/src/Argument/Summary.php(147): League\CLImate\Argument\Summary->argument(Object(League\CLImate\Argument\Argument))
> #1 [internal function]: League\CLImate\Argument\Summary->argumentBracketed(Object(League\CLImate\Argument\Argument))
> #2 phar://C:/PHP7/acme-client.phar/vendor/league/climate/src/Argument/Summary.php(108): array_map(Array, Array)
> #3 phar://C:/PHP7/acme-client.phar/vendor/league/climate/src/Argument/Parser.php(67): League\CLImate\Argument\Summary->short(Array)
> #4 phar://C:/PHP7/acme-client.phar/vendor/league/climate/src/Argument/Manager.php(226): League\CLImate\Argument\Parser->parse(Array)
> #5 phar://C:/PHP7/acme-client.phar/bin/acme(124): League\CLImate\Argument\Manager->parse(Array)
> #6 C:\PHP7\acme-client.phar(2): include('phar://C:/PHP7/...')
> #7 {main}
>   thrown in phar://C:/PHP7/acme-client.phar/vendor/league/climate/src/Argument/Summary.php on line 124

**Comment by Tumbler** [comment]
Using version 0.3.0-beta.4

**Comment by kelunik** [comment]
You'll need the `mbstring` PHP extension, it's usually packaged as `php-mbstring` or similar.
