### ISSUE TITLE
No response for 'domain.org' (MX) from any nameserver after 2 attempts

### ISSUE THREAD

**Issue by IonicaBizau** [kelunik/acme-client#86]
I am getting the following errors when running the setup command: 

```sh
$ php bin/acme setup --server letsencrypt --email support@domain.org
Amp\Dns\TimeoutException: No response for 'domain.org' (MX) from any nameserver after 2 attempts, tried udp://127.0.0.1:53, udp://153.92.2.25:53 in /home/.../acme-client/vendor/amphp/dns/lib/BasicResolver.php:299

Next Kelunik\Acme\AcmeException: Dns query for an MX record on 'domain.org' failed for the following reason: No response for 'domain.org' (MX) from any nameserver after 2 attempts, tried udp://127.0.0.1:53, udp://153.92.2.25:53 in /home/.../acme-client/src/Commands/Setup.php:83

```

I have SSH access to a server provided by Hostinger.

How to solve this?

**Comment by kelunik** [comment]
Could you please share the real domain?

**Comment by IonicaBizau** [comment]
It’s my company website: bloggify.org

**Comment by IonicaBizau** [comment]
`bloggify.org` itself is not hosted on Hostinger, but whatever email I use (even for domains hosted on my Hostinger account), I get the same error.

**Comment by sail1369** [comment]
gmail is also not working

**Comment by juanmalopman** [comment]
Same problem here with hotmail

**Comment by kelunik** [comment]
Could you share your `/etc/resolv.conf`?

**Comment by juanmalopman** [comment]
> Could you share your `/etc/resolv.conf`?

I'm running the script acme-client.phar on a shared hosting. Its `/etc/resolv.conf` has two `nameserver `entries aside from the following:
`options timeout 1 attempts 3`
These are the only three lines of code the file has.

**Comment by IonicaBizau** [comment]
@kelunik It has two nameservers entries too:

```conf
$ cat /etc/resolv.conf
# Ansible managed

nameserver 127.0.0.1
nameserver xxx.xx.x.xx
options timeout 1 attempts 3
```

**Comment by IonicaBizau** [comment]
I am pretty sure that Hostinger blacklisted the domains somehow. In any case, I installed the certificates via Cloudflare.
`acme-client` did work for a few months on Hostinger, but then they changed something I think.

**Comment by kelunik** [comment]
I'll close this, as it seems to be a problem specific to Hostinger and not with the acme-client itself.

**Comment by mrechtien** [comment]
Hi, I'm trying to setup acme-client 1.0.1 on Windows.
The client tries to resolve against a DNS server that is actually not configured.

In belows output <DOMAIN> is the email domain I've used. I tried 3 different Emails, one being a commercial provider, so I assume it's not related to the Email itself.

```
C:\inst\acme-client>php acme-client.phar setup
Amp\Dns\TimeoutException: No response for '<DOMAIN>' (MX) from any nameserver within 3000 ms after 2 attempts, tried udp://172.21.254.254:53, udp://172.21.254.254:53 in phar://C:/server/inst/acme-client/acme-client.phar/vendor/amphp/dns/lib/Rfc1035StubResolver.php:391

Next Kelunik\Acme\AcmeException: Dns query for an MX record on '<DOMAIN>' failed for the following reason: No response for 'dogasoft.de' (MX) from any nameserver within 3000 ms after 2 attempts, tried udp://172.21.254.254:53, udp://172.21.254.254:53 in phar://C:/inst/acme-client/acme-client.phar/src/Commands/Setup.php:122
```
The actual (configured) nameserver is 172.21.11.254.
 -  IPv4-Address  . . . . . . . . . . : 172.32.11.9
 - Subnetmask  . . . . . . . . . . : 255.255.255.0
 - Defaultgateway . . . . . . . . . : 172.32.11.254

As a second test I replaced the primary nameserver with another external one. Still above (not reachable) DNS server was used. 

But after all this might be an AMPHP issue.

**Comment by kelunik** [comment]
@mrechtien This seems to be a different issue. Could you please open a new issue at https://github.com/amphp/dns? Could you also please try to debug where the other IP comes from and why it's used? You can find the logic in https://github.com/amphp/dns/blob/2.x/src/WindowsDnsConfigLoader.php.
