### ISSUE TITLE
Amp\Dns\TimeoutException: No response for 'gmail.com' (MX) from any nameserver after 2 attempts,

### ISSUE THREAD

**Issue by sail1369** [kelunik/acme-client#87]
php bin/acme setup --server letsencrypt --email thepenguinbloggers@gmail.com

code gives the error:::

Amp\Dns\TimeoutException: No response for 'gmail.com' (MX) from any nameserver after 2 attempts, tried udp://127.0.0.1:53, udp://153.92.2.25:53 in /home/0000000/acme-client/vendor/amphp/dns/lib/BasicResolver.php:299

Next Kelunik\Acme\AcmeException: Dns query for an MX record on 'gmail.com' failed for the following reason: No response for 'gmail.com' (MX) from any nameserver after 2 attempts, tried udp://127.0.0.1:53, udp://153.92.2.25:53 in /home/0000000/acme-client/src/Commands/Setup.php:83

Tried to add issue a certificate

**Comment by kelunik** [comment]
Which provider does 153.92.2.25 belong to? I'd like to test with one such server to finally find the underlying cause of this error.

**Comment by sail1369** [comment]
Im using hostinger shared hosting

**Comment by sail1369** [comment]
Ive actually successfully used this on the same domain and worked just fine, i think hostinger may have updated something thats causing this error, namely their MX servers if im right

**Comment by pdt590** [comment]
have same issue

**Comment by rhvsingh** [comment]
Sir, I am also facing the same issue. Please help sir, tell me how to do it.
Hosting: Hostinger Shared Hosting

**Comment by allsilva** [comment]
Também estou com o mesmo problema, alguém já descobriu alguma solução?
I also have the same problem, has anyone found any solution?

**Comment by rhvsingh** [comment]
No sir, not yet

**Comment by kelunik** [comment]
I'll close this, as it seems to be a problem specific to Hostinger and not with the acme-client itself.
